Peter telemetry dev
Northeastern-Electric-Racing/NER pull request #110
Opened 2022-01-31 23:56 UTC by rydzynskip

Created Platformio projects for each of the Teensy CAN nodes, along with initial script for telemetry data handling

2022-02-01 05:23 UTC, mccauleyma requested changes
Overall looks good. Just one random comment on pin numbering

2022-02-01 05:23 UTC, mccauleyma commented on ArduinoCode/Dashboard/Dashboard.ino
> +#define GENERAL_LED_2      1 // custom behavior
Is LED2 = 1 and LED1 = 2 based on schematics? Cause for the sake of satisfaction we can definitely switch it

2022-02-01 05:23 UTC, mccauleyma commented on Embedded Software/Dashboard/src/main.cpp
> +#define GENERAL_LED_2      1 // custom behavior
Same comment as Arduino Code. Is 1 v 2 for a reason?

2022-02-03 18:34 UTC, mccauleyma approved these changes
Yep. We can deal with schematics integration later

2022-02-03 22:25 UTC, nwdepatie approved these changes
We good, I think we can change it as needed during testing and integration

2022-02-03 22:45 UTC, merged