Connection from Shutdown to Indicators, Rewired all grounds to chassis
Northeastern-Electric-Racing/NER pull request #63
Opened 2020-10-28 00:49 UTC by juliusmurphy

The Indicator LEDS outside of the shutdown were removed and now the line goes to two pins in the Driver IO, inside of which they go directly to another set of pins which go out to the LEDs right outside, the LEDs go back in straight to the chassis ground line.

2020-10-28 01:07 UTC, mccauleyma requested changes
Your main changes look good to me overall. 
1) You're changing toggle (-) from a 5V connection to a GND. Did you mean to do that?
2) Toggle (+) is connected to D1, which is kinda a nono (its best to avoid the TX/RX pins)

2020-10-28 01:23 UTC, mccauleyma commented
Oh also, you seem to be lacking the wire between the new hierarchical pins? And you may want to rename them so they are more distinguishable from one another.

2020-10-29 22:19 UTC, mccauleyma approved these changes
Looks good. Hopefully the merge will be fine...

2020-10-29 22:24 UTC, gardnerdy approved these changes

2020-10-29 22:25 UTC, merged