Dylan bms major changes
Northeastern-Electric-Racing/NER pull request #73
Opened 2020-11-11 18:56 UTC by gardnerdy

2020-11-11 19:15 UTC, mccauleyma requested changes
Overall, looks great. Thanks for doing all that.
- (no action needed rn) Accumulator is gonna be next on the queue for a bit of a redraw. It either needs to be spread out over that new space (C size) or redone to fit in the smaller (B size)
- It appears to me that the now "old" BMS-MC schematic still needs to be deleted
- I am not a fan of the MC placement in the master sheet. I would like the MC and BMS enclosure to be near one another and I kinda wanted to keep to the design of HV across the middle and low voltage above/some below. I'd say the CAN line can be bumped right and then there would be room to slide MC back down. You can leave it for me to do later, or do it yourself, whatever works
- Just to confirm that the schematic matches the planned design: Thermistors with a shared ground will be connected somewhere within the harness and there will be a single wire to the PCB? That's what I see schematic wise but I dont recall if we wanted to individually ground to the PCB and then merge on the PCB.

2020-11-11 19:18 UTC, mccauleyma commented
Requested @zperry02 since you work closely with Dylan on this
Requested @rydzynskip as I want you to be aware of what's happening regarding the BMS/MC in case that impacts your plans for CAN wiring

2020-11-13 00:43 UTC, rydzynskip approved these changes

2020-11-13 03:36 UTC, mccauleyma approved these changes
All looks great, thank you for the hard work Dylan!

~ _Aesthetically_ ~ speaking I do like the wire crossings being bumped, however we'll see if we stick to it in the long run. Arguably it's unnecessary extra work and is not how KiCad is intended since it already marks nodes... but I do like it.

2020-11-13 03:36 UTC, merged