Peter pedal box code
Northeastern-Electric-Racing/NER pull request #80
Opened 2020-12-08 21:35 UTC by rydzynskip

Added BMS messages and regenerative braking.

2020-12-08 22:26 UTC, mccauleyma reviewed
Initial impression is good. I just need to know what library to install so I can give it a compile on my machine.

2020-12-09 01:45 UTC, mccauleyma approved these changes
Looks great. Pending testing with the actual CAN installation

2020-12-09 03:46 UTC, jamescd18 requested changes
Overall pretty good! There's a few things I'm curious to get clarification on, but it's minor. Also, not necessarily saying you should do this, but it's easier to read if you order your code in a consistent manner across the function declarations, usages, and function definitions. Basically, since the usage is as simple as looking at the loop() function to see readStates(), readPotentiometers(), and readSwitches(), I would personally choose to use that order in the function declarations and in the function definitions. Again, not suggesting you need to or anything, just point it out.

2020-12-09 03:46 UTC, jamescd18 commented on ArduinoCode/Pedal_Potentiometers/Pedal_Potentiometers.ino
> +    if (canId == CAN_POWER) {
what does CAN_POWER mean?

2020-12-09 04:50 UTC, rydzynskip commented on ArduinoCode/Pedal_Potentiometers/Pedal_Potentiometers.ino
>      canId = CAN.getCanId(); // gets sender ID
No you can't, good catch. I'll change this

2020-12-10 07:55 UTC, jamescd18 approved these changes
Perfect! Makes much more sense now. Also, yeah, saw the buf[8] vs buf[1], but I didn't know enough about C++ to be sure that it could be simplified to just buf[8] which is why I didn't mention it, so great catch there. Looks very good overall, and just next time you can resolve conversation points / comment threads if you feel like you've fixed it or are done with it

2020-12-10 07:56 UTC, merged