Joshua CAN brake light box code
Northeastern-Electric-Racing/NER pull request #81
Opened 2020-12-08 22:39 UTC by joshua2020181

SD card logging

2020-12-09 01:44 UTC, rydzynskip approved these changes
Looks great to me!

2020-12-09 01:44 UTC, mccauleyma approved these changes
Potentially overcomplicating the file naming process, but that's totally fine as long it doesn't cause issues. Schematic needs to be updated to show the SD Card module, and ofc overall this is pending actual testing within the CAN network

2020-12-09 18:34 UTC, jamescd18 reviewed
Very well documented and I appreciate that since it makes everything so much easier to understand what it's doing. No particular issues per se, just optional areas where you could potentially refactor to make it shorter.

2020-12-09 18:34 UTC, jamescd18 commented on ArduinoCode/brake_light_box/brake_light_box.ino
> +  digitalWrite(SD_SS_PIN, LOW); // enable SD module
this chunk could be a cool candidate for turning it into a separate `switchCANToSD()` function if you wanted. Totally optional.

2020-12-09 18:34 UTC, jamescd18 commented on ArduinoCode/brake_light_box/brake_light_box.ino
> +*/
```suggestion
/**
 * Sets relavent pins to output or input, initializes serial for debugging, initializes CAN, SD card reader,
 * determines proper file name for future logs.
 */
```

2020-12-09 18:34 UTC, jamescd18 commented on ArduinoCode/brake_light_box/brake_light_box.ino
> +*/
```suggestion
/**
 * Deals with incoming CAN messages, if an error is recieved, it is logged. Writes to SD card every 30 seconds.
 */
```

2020-12-09 18:34 UTC, jamescd18 commented on ArduinoCode/brake_light_box/brake_light_box.ino
> +*/
```suggestion
/**
 * Compiles errors, writes to SD every 5 errors
 *
 * @param id the sender id of the error
 * @param error the errors to be logged
 */
```

2020-12-09 18:34 UTC, jamescd18 commented on ArduinoCode/brake_light_box/brake_light_box.ino
> +*/
```suggestion
/**
 * Logs errors to SD card.
 *
 * @param errors the error(s) to be logged
 * @returns true if logging was successful, false if it failed
 */
```

2020-12-10 07:59 UTC, jamescd18 requested changes
@rydzynskip can you confirm whether or not the suggestions I've made are correct? I just wanna be sure before pushing it all through

2020-12-10 07:59 UTC, jamescd18 commented on ArduinoCode/brake_light_box/brake_light_box.ino
> + * Activates CAN module and deactivates SD module
```suggestion
 * Deactivates SD module and then activates CAN module
```

2020-12-10 07:59 UTC, jamescd18 commented on ArduinoCode/brake_light_box/brake_light_box.ino
> + * Activates SD module and deactivates CAN module
```suggestion
 * Deactivates CAN module and then activates SD module
```

2020-12-11 02:25 UTC, rydzynskip commented
The brake light schematic was updated so this was to assign the correct pins in the code.

2020-12-14 20:58 UTC, jamescd18 approved these changes
Looks good. Whoopsies on my part for the delay.

2020-12-14 20:59 UTC, merged