Update Pedal_Box.ino
Northeastern-Electric-Racing/NER pull request #89
Opened 2021-02-10 00:48 UTC by jackHeun

Checks for open and short circuit for potentiometer.

2021-02-10 01:15 UTC, jamescd18 requested changes
Minor fix needed

2021-02-10 01:15 UTC, jamescd18 commented on ArduinoCode/Pedal_Box/Pedal_Box.ino
> +  if(accelPin1Val || accelPin2Val == 0){
```suggestion
  if(accelPin1Val == 0 || accelPin2Val == 0){
```
Pretty sure that the left and right side of the double pipe or operator both need to be booleans.

2021-02-10 01:15 UTC, jamescd18 commented on ArduinoCode/Pedal_Box/Pedal_Box.ino
> +  if(accelPin1Val || accelPin2Val == 1023){
```suggestion
  if(accelPin1Val == 1023 || accelPin2Val == 1023){
```
Same as above.

2021-02-10 03:00 UTC, rydzynskip requested changes

2021-02-10 03:00 UTC, rydzynskip commented on ArduinoCode/Pedal_Box/Pedal_Box.ino
>    if (abs(accelPin1Val - accelPin2Val) <= (1024 * 0.1)) {
Good catch with the 1023 potentiometer value. This line can also be changed

2021-02-16 22:59 UTC, rydzynskip approved these changes

2021-03-10 22:57 UTC, jamescd18 approved these changes
oops, yeah, looks good. if I hadn't been so slow with providing review, I would suggest reducing code duplication here by including all four checks OR'ed together in one if block, unless my understanding of the code is wrong

2021-03-11 04:40 UTC, merged